AWSTemplateFormatVersion: 2010-09-09
Description: 'CloudFormation Stack to deploy the serverless backend for the wild-ryde webapp'
Parameters:
  UserManagementStackName:
    Description: 'Stack name of user management stack'
    Type: String
Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties: 
      Name: WildRydes
      EndpointConfiguration: 
        Types:
        - EDGE
  RideApiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt 
      - RestApi
      - RootResourceId
      PathPart: ride
  OptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref RideApiResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  PostMethod:
    Type: AWS::ApiGateway::Method
    Properties: 
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref Authorizer
      Integration: 
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: String
        PassthroughBehavior: WHEN_NO_MATCH
        ContentHandling: CONVERT_TO_TEXT
        TimeoutInMillis: 29000
        IntegrationResponses: 
        - StatusCode: '200' 
          ResponseTemplates:
            application/json: null
      MethodResponses: 
      - StatusCode: '200' 
        ResponseModels:
          application/json: 'Empty'
      RestApiId: !Ref RestApi
      ResourceId: !Ref RideApiResource
  Deployment:
    DependsOn:
    - OptionsMethod
    - PostMethod
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref RestApi
      StageName: prod
  Authorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      RestApiId: !Ref RestApi
      Name: WildRydes
      Type: COGNITO_USER_POOLS
      AuthType: cognito_user_pools
      IdentitySource: method.request.header.Authorization
      ProviderArns:
      - Fn::ImportValue:
          !Sub "${UserManagementStackName}-CognitoUserPollArn"

Outputs:
  ProdEndpoint:
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
